### ISSUE TITLE
static image file not served by dev server

### ISSUE THREAD

**Issue by fredcy** [elwin013/parcel-reporter-static-files-copy#10]
I set this up to copy a logo.png file from the `static` directory. That logo image is sourced by HTML generated at runtime by an Elm app. This works fine for the production build -- dist/logo.png is created and is served as needed at runtime as a static file by the production web server. But `parcel serve` does not serve the file and so I get a broken image. If I run `curl http://localhost:1234/logo.png` I get an HTTP 200 response with the contents of my entry index.html file. What can I do to get this static file to be served properly by `parcel serve`?

**Comment by damianobarbati** [comment]
@fredcy did you find a solution?

**Comment by fredcy** [comment]
No, I am still stuck on this. My dev instance just displays a broken logo image.

**Comment by elwin013** [comment]
Hey,
this is current limitation of the plugin - it only copies files from directory A to directory B. There is no adding any assets into bundle graph, so no watching file and no serving by default development server. 

Further explanation - If we look into embedded server code it takes bundle graph, search through it and:
* if found file with matching path - it returns it,
* otherwise returns index.

So, in your case `logo.png` doesn't exists in bundle graph and is not served by development server.

If you don't care about HMR you can use other way to serve `dist` folder, for example python3 onliner: `python -m http.server 8000`.

**Comment by fredcy** [comment]
I see. I have used python http.server to verify that all is well in the dev environment, but I really want live watch/reloads of the non-static content there for most development work.  So it seems I have to live with the broken image (and other assets) in dev mode if I want to use Parcel.

Given this problem I tried using Snowpack instead and that's working well. So I'm no longer stuck.

**Comment by ndahn** [comment]
This has caused me so many headaches! I was fetching a resource and always got my _index.html_ with no warning whatsoever :/

**Comment by elwin013** [comment]
Wohoo! I can see that with latest version of Parcel (`2.0.0-rc.0`) built-in dev server is serving files from dist directory. 

For example serving `examples/default`  and accessing `http://localhost:1234/magic/magic.txt` will gives us `magic.txt` file as expected! :-) 

Limitation stated in README.md (no watcher, only copy on build finish) is still in place.

cc: @fredcy @ndahn @damianobarbati
